2019-06-25 17:45:32,834 - DEBUG - tty.usbmodem0006822145041: Writing: 105 bytearray(b'c&\x9c\x16j\x9a~\nc\xfd:\x81\xa5\xb1\xad\xc5v\xb860\xf8\x9a\x02\xb9TAw\xb8L\xd6\xbe8Y\xf8\x00=\x8f8\xf0\xef\xcd\xf7\xf2\x0f\xc6\xe4\xc5m\xbd\x04\x15\x86\xd2\xe4Uz\xe4\x8eF\xc7Qi\xec\x92\xa1\xect\xf2U\x1a\xa9\x8e\x17\xdd~7\xbdw\x94n\x82\xe8:r\xabeH\x8fE#+\xacZEO\x0b')
2019-06-25 17:45:32,834 - DEBUG - tty.usbmodem0006822145041: TX: 616963269c166a9a7e0a63fd3a81a5b1adc576b83630f89a02b9544177b84cd6be3859f8003d8f38f0efcdf7f20fc6e4c56dbd041586d2e4557ae48e46c75169ec92a1ec74f2551aa98e17dd7e37bd77946e82e83a72ab65488f45232bac5a454f0b
2019-06-25 17:45:32,845 - DEBUG - tty.usbmodem0006822145041: RX: 03845384
2019-06-25 17:45:32,845 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: CmdRsp, data: {'opcode': 83, 'status': 132, 'data': bytearray(b'')}}
2019-06-25 17:45:32,846 - ERROR - tty.usbmodem0006822145041: None: ERROR_INVALID_LENGTH
2019-06-25 17:45:32,846 - DEBUG - tty.usbmodem0006822145041: Writing: 159 bytearray(b'\x01\x00\x01\x00')
2019-06-25 17:45:32,846 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.__event_handler of <__main__.Manager object at 0x1050d9160>>
2019-06-25 17:45:32,846 - DEBUG - tty.usbmodem0006822145041: TX: 059f01000100
2019-06-25 17:45:32,847 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 227, in __event_handler
    if event._opcode == ConfigurationClient._COMPOSITION_DATA_STATUS:
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/mesh/access.py", line 94, in __eq__
    return (self.serialize == other.serialize())
AttributeError: 'int' object has no attribute 'serialize'

2019-06-25 17:45:32,847 - DEBUG - tty.usbmodem0006822145041: RX: 03840084
2019-06-25 17:45:32,847 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: CmdRsp, data: {'opcode': 0, 'status': 132, 'data': bytearray(b'')}}
2019-06-25 17:45:32,847 - ERROR - tty.usbmodem0006822145041: None: ERROR_INVALID_LENGTH
2019-06-25 17:45:32,847 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.__event_handler of <__main__.Manager object at 0x1050d9160>>
2019-06-25 17:45:32,848 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 227, in __event_handler
    if event._opcode == ConfigurationClient._COMPOSITION_DATA_STATUS:
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/mesh/access.py", line 94, in __eq__
    return (self.serialize == other.serialize())
AttributeError: 'int' object has no attribute 'serialize'

2019-06-25 17:45:32,848 - DEBUG - tty.usbmodem0006822145041: Writing: 146 bytearray(b'\x00\x00\x18\xee\xd9\xc2\xa5j\xdd\x85\x04\x9f\xfc<Y\xad\x0e\x12')
2019-06-25 17:45:32,848 - DEBUG - tty.usbmodem0006822145041: TX: 1392000018eed9c2a56add85049ffc3c59ad0e12
2019-06-25 17:45:32,848 - DEBUG - tty.usbmodem0006822145041: RX: 03840084
2019-06-25 17:45:32,848 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: CmdRsp, data: {'opcode': 0, 'status': 132, 'data': bytearray(b'')}}
2019-06-25 17:45:32,848 - ERROR - tty.usbmodem0006822145041: None: ERROR_INVALID_LENGTH
2019-06-25 17:45:32,848 - DEBUG - tty.usbmodem0006822145041: Writing: 151 bytearray(b'\x00\x00\x00\x00Oh\xad\x85\xd9\xf4\x8a\xc8X\x9d\xf6e\xb6\xb4\x9b\x8a')
2019-06-25 17:45:32,848 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.__event_handler of <__main__.Manager object at 0x1050d9160>>
2019-06-25 17:45:32,849 - DEBUG - tty.usbmodem0006822145041: TX: 1597000000004f68ad85d9f48ac8589df665b6b49b8a
2019-06-25 17:45:32,849 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 227, in __event_handler
    if event._opcode == ConfigurationClient._COMPOSITION_DATA_STATUS:
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/mesh/access.py", line 94, in __eq__
    return (self.serialize == other.serialize())
AttributeError: 'int' object has no attribute 'serialize'

2019-06-25 17:45:32,849 - DEBUG - tty.usbmodem0006822145041: RX: 03840084
2019-06-25 17:45:32,849 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: CmdRsp, data: {'opcode': 0, 'status': 132, 'data': bytearray(b'')}}
2019-06-25 17:45:32,849 - ERROR - tty.usbmodem0006822145041: None: ERROR_INVALID_LENGTH
2019-06-25 17:45:32,850 - DEBUG - tty.usbmodem0006822145041: Writing: 151 bytearray(b'\x01\x00\x00\x00*\xa2\xa6\xde\xd5\xa0y\x8c\xea\xb5x|\xa3\xae9\xfc')
2019-06-25 17:45:32,850 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.__event_handler of <__main__.Manager object at 0x1050d9160>>
2019-06-25 17:45:32,850 - DEBUG - tty.usbmodem0006822145041: TX: 1597010000002aa2a6ded5a0798ceab5787ca3ae39fc
2019-06-25 17:45:32,850 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 227, in __event_handler
    if event._opcode == ConfigurationClient._COMPOSITION_DATA_STATUS:
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/mesh/access.py", line 94, in __eq__
    return (self.serialize == other.serialize())
AttributeError: 'int' object has no attribute 'serialize'

2019-06-25 17:45:32,851 - DEBUG - tty.usbmodem0006822145041: RX: 03840084
2019-06-25 17:45:32,852 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: CmdRsp, data: {'opcode': 0, 'status': 132, 'data': bytearray(b'')}}
2019-06-25 17:45:32,852 - ERROR - tty.usbmodem0006822145041: None: ERROR_INVALID_LENGTH
2019-06-25 17:45:32,852 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.__event_handler of <__main__.Manager object at 0x1050d9160>>
2019-06-25 17:45:32,853 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 227, in __event_handler
    if event._opcode == ConfigurationClient._COMPOSITION_DATA_STATUS:
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/mesh/access.py", line 94, in __eq__
    return (self.serialize == other.serialize())
AttributeError: 'int' object has no attribute 'serialize'

2019-06-25 17:45:32,854 - DEBUG - tty.usbmodem0006822145041: RX: 03840084
2019-06-25 17:45:32,855 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: CmdRsp, data: {'opcode': 0, 'status': 132, 'data': bytearray(b'')}}
2019-06-25 17:45:32,855 - ERROR - tty.usbmodem0006822145041: None: ERROR_INVALID_LENGTH
2019-06-25 17:45:32,856 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.__event_handler of <__main__.Manager object at 0x1050d9160>>
2019-06-25 17:45:32,858 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 227, in __event_handler
    if event._opcode == ConfigurationClient._COMPOSITION_DATA_STATUS:
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/mesh/access.py", line 94, in __eq__
    return (self.serialize == other.serialize())
AttributeError: 'int' object has no attribute 'serialize'

2019-06-25 17:45:32,858 - DEBUG - tty.usbmodem0006822145041: RX: 03840084
2019-06-25 17:45:32,858 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: CmdRsp, data: {'opcode': 0, 'status': 132, 'data': bytearray(b'')}}
2019-06-25 17:45:32,859 - ERROR - tty.usbmodem0006822145041: None: ERROR_INVALID_LENGTH
2019-06-25 17:45:32,859 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.__event_handler of <__main__.Manager object at 0x1050d9160>>
2019-06-25 17:45:32,859 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 227, in __event_handler
    if event._opcode == ConfigurationClient._COMPOSITION_DATA_STATUS:
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/mesh/access.py", line 94, in __eq__
    return (self.serialize == other.serialize())
AttributeError: 'int' object has no attribute 'serialize'

2019-06-25 17:45:32,859 - DEBUG - tty.usbmodem0006822145041: RX: 03840084
2019-06-25 17:45:32,859 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: CmdRsp, data: {'opcode': 0, 'status': 132, 'data': bytearray(b'')}}
2019-06-25 17:45:32,860 - ERROR - tty.usbmodem0006822145041: None: ERROR_INVALID_LENGTH
2019-06-25 17:45:32,860 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.__event_handler of <__main__.Manager object at 0x1050d9160>>
2019-06-25 17:45:32,860 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 227, in __event_handler
    if event._opcode == ConfigurationClient._COMPOSITION_DATA_STATUS:
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/mesh/access.py", line 94, in __eq__
    return (self.serialize == other.serialize())
AttributeError: 'int' object has no attribute 'serialize'

2019-06-25 17:45:32,860 - DEBUG - tty.usbmodem0006822145041: RX: 03840084
2019-06-25 17:45:32,860 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: CmdRsp, data: {'opcode': 0, 'status': 132, 'data': bytearray(b'')}}
2019-06-25 17:45:32,860 - ERROR - tty.usbmodem0006822145041: None: ERROR_INVALID_LENGTH
2019-06-25 17:45:32,860 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.__event_handler of <__main__.Manager object at 0x1050d9160>>
2019-06-25 17:45:32,860 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 227, in __event_handler
    if event._opcode == ConfigurationClient._COMPOSITION_DATA_STATUS:
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/mesh/access.py", line 94, in __eq__
    return (self.serialize == other.serialize())
AttributeError: 'int' object has no attribute 'serialize'

2019-06-25 17:45:32,860 - DEBUG - tty.usbmodem0006822145041: RX: 03840084
2019-06-25 17:45:32,861 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: CmdRsp, data: {'opcode': 0, 'status': 132, 'data': bytearray(b'')}}
2019-06-25 17:45:32,861 - ERROR - tty.usbmodem0006822145041: None: ERROR_INVALID_LENGTH
2019-06-25 17:45:32,861 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.__event_handler of <__main__.Manager object at 0x1050d9160>>
2019-06-25 17:45:32,861 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 227, in __event_handler
    if event._opcode == ConfigurationClient._COMPOSITION_DATA_STATUS:
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/mesh/access.py", line 94, in __eq__
    return (self.serialize == other.serialize())
AttributeError: 'int' object has no attribute 'serialize'

2019-06-25 17:45:32,861 - DEBUG - tty.usbmodem0006822145041: RX: 03840084
2019-06-25 17:45:32,861 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: CmdRsp, data: {'opcode': 0, 'status': 132, 'data': bytearray(b'')}}
2019-06-25 17:45:32,861 - ERROR - tty.usbmodem0006822145041: None: ERROR_INVALID_LENGTH
2019-06-25 17:45:32,861 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.__event_handler of <__main__.Manager object at 0x1050d9160>>
2019-06-25 17:45:32,861 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 227, in __event_handler
    if event._opcode == ConfigurationClient._COMPOSITION_DATA_STATUS:
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/mesh/access.py", line 94, in __eq__
    return (self.serialize == other.serialize())
AttributeError: 'int' object has no attribute 'serialize'

2019-06-25 17:45:32,861 - DEBUG - tty.usbmodem0006822145041: RX: 03840084
2019-06-25 17:45:32,861 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: CmdRsp, data: {'opcode': 0, 'status': 132, 'data': bytearray(b'')}}
2019-06-25 17:45:32,862 - ERROR - tty.usbmodem0006822145041: None: ERROR_INVALID_LENGTH
2019-06-25 17:45:32,862 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.__event_handler of <__main__.Manager object at 0x1050d9160>>
2019-06-25 17:45:32,862 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 227, in __event_handler
    if event._opcode == ConfigurationClient._COMPOSITION_DATA_STATUS:
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/mesh/access.py", line 94, in __eq__
    return (self.serialize == other.serialize())
AttributeError: 'int' object has no attribute 'serialize'

2019-06-25 17:45:32,862 - DEBUG - tty.usbmodem0006822145041: RX: 03840084
2019-06-25 17:45:32,862 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: CmdRsp, data: {'opcode': 0, 'status': 132, 'data': bytearray(b'')}}
2019-06-25 17:45:32,862 - ERROR - tty.usbmodem0006822145041: None: ERROR_INVALID_LENGTH
2019-06-25 17:45:32,862 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.__event_handler of <__main__.Manager object at 0x1050d9160>>
2019-06-25 17:45:32,862 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 227, in __event_handler
    if event._opcode == ConfigurationClient._COMPOSITION_DATA_STATUS:
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/mesh/access.py", line 94, in __eq__
    return (self.serialize == other.serialize())
AttributeError: 'int' object has no attribute 'serialize'

2019-06-25 17:45:32,862 - DEBUG - tty.usbmodem0006822145041: RX: 03849f8e
2019-06-25 17:45:32,862 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: CmdRsp, data: {'opcode': 159, 'status': 142, 'data': bytearray(b'')}}
2019-06-25 17:45:32,862 - ERROR - tty.usbmodem0006822145041: None: ERROR_REJECTED
2019-06-25 17:45:32,862 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.__event_handler of <__main__.Manager object at 0x1050d9160>>
2019-06-25 17:45:32,863 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 227, in __event_handler
    if event._opcode == ConfigurationClient._COMPOSITION_DATA_STATUS:
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/mesh/access.py", line 94, in __eq__
    return (self.serialize == other.serialize())
AttributeError: 'int' object has no attribute 'serialize'

2019-06-25 17:45:32,863 - DEBUG - tty.usbmodem0006822145041: RX: 03849281
2019-06-25 17:45:32,863 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: CmdRsp, data: {'opcode': 146, 'status': 129, 'data': bytearray(b'')}}
2019-06-25 17:45:32,863 - ERROR - tty.usbmodem0006822145041: SubnetAdd: ERROR_INTERNAL
2019-06-25 17:45:32,863 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.__event_handler of <__main__.Manager object at 0x1050d9160>>
2019-06-25 17:45:32,863 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 227, in __event_handler
    if event._opcode == ConfigurationClient._COMPOSITION_DATA_STATUS:
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/mesh/access.py", line 94, in __eq__
    return (self.serialize == other.serialize())
AttributeError: 'int' object has no attribute 'serialize'

2019-06-25 17:45:32,863 - DEBUG - tty.usbmodem0006822145041: RX: 03849781
2019-06-25 17:45:32,863 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: CmdRsp, data: {'opcode': 151, 'status': 129, 'data': bytearray(b'')}}
2019-06-25 17:45:32,863 - ERROR - tty.usbmodem0006822145041: AppkeyAdd: ERROR_INTERNAL
2019-06-25 17:45:32,864 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.__event_handler of <__main__.Manager object at 0x1050d9160>>
2019-06-25 17:45:32,864 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 227, in __event_handler
    if event._opcode == ConfigurationClient._COMPOSITION_DATA_STATUS:
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/mesh/access.py", line 94, in __eq__
    return (self.serialize == other.serialize())
AttributeError: 'int' object has no attribute 'serialize'

2019-06-25 17:45:32,864 - DEBUG - tty.usbmodem0006822145041: RX: 03849781
2019-06-25 17:45:32,864 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: CmdRsp, data: {'opcode': 151, 'status': 129, 'data': bytearray(b'')}}
2019-06-25 17:45:32,864 - ERROR - tty.usbmodem0006822145041: AppkeyAdd: ERROR_INTERNAL
2019-06-25 17:45:32,864 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.__event_handler of <__main__.Manager object at 0x1050d9160>>
2019-06-25 17:45:32,864 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 227, in __event_handler
    if event._opcode == ConfigurationClient._COMPOSITION_DATA_STATUS:
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/mesh/access.py", line 94, in __eq__
    return (self.serialize == other.serialize())
AttributeError: 'int' object has no attribute 'serialize'

2019-06-25 17:45:34,304 - DEBUG - tty.usbmodem0006822145041: Writing: 97 bytearray(b'')
2019-06-25 17:45:34,304 - DEBUG - tty.usbmodem0006822145041: TX: 0161
2019-06-25 17:45:34,306 - DEBUG - tty.usbmodem0006822145041: RX: 03846100
2019-06-25 17:45:34,306 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: CmdRsp, data: {'opcode': 97, 'status': 0, 'data': bytearray(b'')}}
2019-06-25 17:45:34,306 - INFO - tty.usbmodem0006822145041: Success
2019-06-25 17:45:34,306 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.__event_handler of <__main__.Manager object at 0x1050d9160>>
2019-06-25 17:45:34,307 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 227, in __event_handler
    if event._opcode == ConfigurationClient._COMPOSITION_DATA_STATUS:
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/mesh/access.py", line 94, in __eq__
    return (self.serialize == other.serialize())
AttributeError: 'int' object has no attribute 'serialize'

2019-06-25 17:45:34,803 - DEBUG - tty.usbmodem0006822145041: RX: 1ac09db77a0526b8734988639509c242d107c90001c8639509c2c2
2019-06-25 17:45:34,803 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: ProvUnprovisionedReceived, data: {'uuid': bytearray(b'\x9d\xb7z\x05&\xb8sI\x88c\x95\t\xc2B\xd1\x07'), 'rssi': -55, 'gatt_supported': 0, 'adv_addr_type': 1, 'adv_addr': bytearray(b'\xc8c\x95\t\xc2\xc2')}}
2019-06-25 17:45:34,803 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.__event_handler of <__main__.Manager object at 0x1050d9160>>
2019-06-25 17:45:34,804 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 227, in __event_handler
    if event._opcode == ConfigurationClient._COMPOSITION_DATA_STATUS:
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/mesh/access.py", line 94, in __eq__
    return (self.serialize == other.serialize())
AttributeError: 'int' object has no attribute 'serialize'

2019-06-25 17:45:34,804 - INFO - tty.usbmodem0006822145041: Received UUID 9db77a0526b8734988639509c242d107 with RSSI: -55 dB
2019-06-25 17:45:36,814 - DEBUG - tty.usbmodem0006822145041: RX: 1ac09db77a0526b8734988639509c242d107cb0001c8639509c2c2
2019-06-25 17:45:36,814 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: ProvUnprovisionedReceived, data: {'uuid': bytearray(b'\x9d\xb7z\x05&\xb8sI\x88c\x95\t\xc2B\xd1\x07'), 'rssi': -53, 'gatt_supported': 0, 'adv_addr_type': 1, 'adv_addr': bytearray(b'\xc8c\x95\t\xc2\xc2')}}
2019-06-25 17:45:36,814 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.__event_handler of <__main__.Manager object at 0x1050d9160>>
2019-06-25 17:45:36,814 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 227, in __event_handler
    if event._opcode == ConfigurationClient._COMPOSITION_DATA_STATUS:
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/mesh/access.py", line 94, in __eq__
    return (self.serialize == other.serialize())
AttributeError: 'int' object has no attribute 'serialize'

2019-06-25 17:45:37,311 - DEBUG - tty.usbmodem0006822145041: Writing: 98 bytearray(b'')
2019-06-25 17:45:37,317 - DEBUG - tty.usbmodem0006822145041: TX: 0162
2019-06-25 17:45:37,336 - DEBUG - tty.usbmodem0006822145041: Writing: 99 bytearray(b'\x00\x9d\xb7z\x05&\xb8sI\x88c\x95\t\xc2B\xd1\x07\x18\xee\xd9\xc2\xa5j\xdd\x85\x04\x9f\xfc<Y\xad\x0e\x12\x00\x00\x00\x00\x00\x00 \x00\x00\x00\x00')
2019-06-25 17:45:37,347 - DEBUG - tty.usbmodem0006822145041: TX: 2d63009db77a0526b8734988639509c242d10718eed9c2a56add85049ffc3c59ad0e120000000000002000000000
2019-06-25 17:45:37,347 - DEBUG - tty.usbmodem0006822145041: RX: 03846200
2019-06-25 17:45:37,354 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: CmdRsp, data: {'opcode': 98, 'status': 0, 'data': bytearray(b'')}}
2019-06-25 17:45:37,354 - INFO - tty.usbmodem0006822145041: Success
2019-06-25 17:45:37,354 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.__event_handler of <__main__.Manager object at 0x1050d9160>>
2019-06-25 17:45:37,377 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 227, in __event_handler
    if event._opcode == ConfigurationClient._COMPOSITION_DATA_STATUS:
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/mesh/access.py", line 94, in __eq__
    return (self.serialize == other.serialize())
AttributeError: 'int' object has no attribute 'serialize'

2019-06-25 17:45:37,437 - DEBUG - tty.usbmodem0006822145041: RX: 0484630000
2019-06-25 17:45:37,443 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: CmdRsp, data: {'opcode': 99, 'status': 0, 'data': bytearray(b'\x00')}}
2019-06-25 17:45:37,449 - INFO - tty.usbmodem0006822145041: Provision: {'context': 0}
2019-06-25 17:45:37,455 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.__event_handler of <__main__.Manager object at 0x1050d9160>>
2019-06-25 17:45:37,477 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 227, in __event_handler
    if event._opcode == ConfigurationClient._COMPOSITION_DATA_STATUS:
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/mesh/access.py", line 94, in __eq__
    return (self.serialize == other.serialize())
AttributeError: 'int' object has no attribute 'serialize'

2019-06-25 17:45:37,478 - DEBUG - tty.usbmodem0006822145041: RX: 02c100
2019-06-25 17:45:37,483 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: ProvLinkEstablished, data: {'context_id': 0}}
2019-06-25 17:45:37,484 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.__event_handler of <__main__.Manager object at 0x1050d9160>>
2019-06-25 17:45:37,500 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 227, in __event_handler
    if event._opcode == ConfigurationClient._COMPOSITION_DATA_STATUS:
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/mesh/access.py", line 94, in __eq__
    return (self.serialize == other.serialize())
AttributeError: 'int' object has no attribute 'serialize'

2019-06-25 17:45:37,505 - INFO - tty.usbmodem0006822145041: Link established
2019-06-25 17:45:37,511 - DEBUG - tty.usbmodem0006822145041: RX: 0bc300010001000000000000
2019-06-25 17:45:37,511 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: ProvCapsReceived, data: {'context_id': 0, 'num_elements': 1, 'public_key_type': 0, 'static_oob_types': 1, 'output_oob_size': 0, 'output_oob_actions': 0, 'input_oob_size': 0, 'input_oob_actions': 0}}
2019-06-25 17:45:37,511 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.__event_handler of <__main__.Manager object at 0x1050d9160>>
2019-06-25 17:45:37,511 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 227, in __event_handler
    if event._opcode == ConfigurationClient._COMPOSITION_DATA_STATUS:
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/mesh/access.py", line 94, in __eq__
    return (self.serialize == other.serialize())
AttributeError: 'int' object has no attribute 'serialize'

2019-06-25 17:45:37,511 - INFO - tty.usbmodem0006822145041: Received capabilities
2019-06-25 17:45:37,511 - INFO - tty.usbmodem0006822145041: Number of elements: 1
2019-06-25 17:45:37,511 - DEBUG - tty.usbmodem0006822145041: Writing: 102 bytearray(b'\x00\x00\x00\x00')
2019-06-25 17:45:37,512 - DEBUG - tty.usbmodem0006822145041: TX: 056600000000
2019-06-25 17:45:37,514 - DEBUG - tty.usbmodem0006822145041: RX: 0484660000
2019-06-25 17:45:37,514 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: CmdRsp, data: {'opcode': 102, 'status': 0, 'data': bytearray(b'\x00')}}
2019-06-25 17:45:37,514 - INFO - tty.usbmodem0006822145041: OobUse: {'context': 0}
2019-06-25 17:45:37,514 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.__event_handler of <__main__.Manager object at 0x1050d9160>>
2019-06-25 17:45:37,515 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 227, in __event_handler
    if event._opcode == ConfigurationClient._COMPOSITION_DATA_STATUS:
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/mesh/access.py", line 94, in __eq__
    return (self.serialize == other.serialize())
AttributeError: 'int' object has no attribute 'serialize'

2019-06-25 17:45:39,708 - DEBUG - tty.usbmodem0006822145041: RX: 62c700df33931aa8ee8ff422102222eee825eb0db27961a9d62cb5043847a5673687f5d749dfbfb1cd922ab9ee7c6db528fb728473899ec40c4ee6bcbb333f32bb4af5fe237cd28f3f17e7ec8911041687c75d535ac944e5dc849bc375bf851d4fab2a
2019-06-25 17:45:39,709 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: ProvEcdhRequest, data: {'context_id': 0, 'peer_public': bytearray(b'\xdf3\x93\x1a\xa8\xee\x8f\xf4"\x10""\xee\xe8%\xeb\r\xb2ya\xa9\xd6,\xb5\x048G\xa5g6\x87\xf5\xd7I\xdf\xbf\xb1\xcd\x92*\xb9\xee|m\xb5(\xfbr\x84s\x89\x9e\xc4\x0cN\xe6\xbc\xbb3?2\xbbJ\xf5'), 'node_private': bytearray(b'\xfe#|\xd2\x8f?\x17\xe7\xec\x89\x11\x04\x16\x87\xc7]SZ\xc9D\xe5\xdc\x84\x9b\xc3u\xbf\x85\x1dO\xab*')}}
2019-06-25 17:45:39,710 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.__event_handler of <__main__.Manager object at 0x1050d9160>>
2019-06-25 17:45:39,710 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 227, in __event_handler
    if event._opcode == ConfigurationClient._COMPOSITION_DATA_STATUS:
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/mesh/access.py", line 94, in __eq__
    return (self.serialize == other.serialize())
AttributeError: 'int' object has no attribute 'serialize'

2019-06-25 17:45:39,710 - INFO - tty.usbmodem0006822145041: ECDH request received
2019-06-25 17:45:39,714 - DEBUG - tty.usbmodem0006822145041: Writing: 104 bytearray(b'\x00\x14\xf7\x9c\x0b\xfeF\xd5X\x80\xeb\x12\xba\xc2?\x97\x9d-/\xbc)\x02I\xb9\xf4\x16\xeb\x9b\xc7\xa7\x17:i')
2019-06-25 17:45:39,714 - DEBUG - tty.usbmodem0006822145041: TX: 22680014f79c0bfe46d55880eb12bac23f979d2d2fbc290249b9f416eb9bc7a7173a69
2019-06-25 17:45:39,719 - DEBUG - tty.usbmodem0006822145041: RX: 0484680000
2019-06-25 17:45:39,719 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: CmdRsp, data: {'opcode': 104, 'status': 0, 'data': bytearray(b'\x00')}}
2019-06-25 17:45:39,719 - INFO - tty.usbmodem0006822145041: EcdhSecret: {'context': 0}
2019-06-25 17:45:39,719 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.__event_handler of <__main__.Manager object at 0x1050d9160>>
2019-06-25 17:45:39,720 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 227, in __event_handler
    if event._opcode == ConfigurationClient._COMPOSITION_DATA_STATUS:
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/mesh/access.py", line 94, in __eq__
    return (self.serialize == other.serialize())
AttributeError: 'int' object has no attribute 'serialize'

2019-06-25 17:45:40,052 - DEBUG - tty.usbmodem0006822145041: RX: 2cc5000000000000002000000034a589c3e5cfce7a13c63aa6c6018f9a18eed9c2a56add85049ffc3c59ad0e12
2019-06-25 17:45:40,052 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: ProvComplete, data: {'context_id': 0, 'iv_index': 0, 'net_key_index': 0, 'address': 32, 'iv_update_flag': 0, 'key_refresh_flag': 0, 'device_key': bytearray(b'4\xa5\x89\xc3\xe5\xcf\xcez\x13\xc6:\xa6\xc6\x01\x8f\x9a'), 'net_key': bytearray(b'\x18\xee\xd9\xc2\xa5j\xdd\x85\x04\x9f\xfc<Y\xad\x0e\x12')}}
2019-06-25 17:45:40,053 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.__event_handler of <__main__.Manager object at 0x1050d9160>>
2019-06-25 17:45:40,053 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 227, in __event_handler
    if event._opcode == ConfigurationClient._COMPOSITION_DATA_STATUS:
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/mesh/access.py", line 94, in __eq__
    return (self.serialize == other.serialize())
AttributeError: 'int' object has no attribute 'serialize'

2019-06-25 17:45:40,053 - INFO - tty.usbmodem0006822145041: Provisioning complete
2019-06-25 17:45:40,053 - INFO - tty.usbmodem0006822145041: 	Address(es): 0x20-0x20
2019-06-25 17:45:40,053 - INFO - tty.usbmodem0006822145041: 	Device key: 34a589c3e5cfce7a13c63aa6c6018f9a
2019-06-25 17:45:40,053 - INFO - tty.usbmodem0006822145041: 	Network key: 18eed9c2a56add85049ffc3c59ad0e12
2019-06-25 17:45:40,053 - INFO - tty.usbmodem0006822145041: Adding device key to subnet 0
2019-06-25 17:45:40,053 - INFO - tty.usbmodem0006822145041: Adding publication address of root element
2019-06-25 17:45:40,054 - DEBUG - tty.usbmodem0006822145041: Writing: 156 bytearray(b' \x00\x00\x004\xa5\x89\xc3\xe5\xcf\xcez\x13\xc6:\xa6\xc6\x01\x8f\x9a')
2019-06-25 17:45:40,054 - DEBUG - tty.usbmodem0006822145041: TX: 159c2000000034a589c3e5cfce7a13c63aa6c6018f9a
2019-06-25 17:45:40,054 - DEBUG - tty.usbmodem0006822145041: Writing: 164 bytearray(b' \x00')
2019-06-25 17:45:40,054 - DEBUG - tty.usbmodem0006822145041: TX: 03a42000
2019-06-25 17:45:40,059 - DEBUG - tty.usbmodem0006822145041: RX: 05849c000800
2019-06-25 17:45:40,059 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: CmdRsp, data: {'opcode': 156, 'status': 0, 'data': bytearray(b'\x08\x00')}}
2019-06-25 17:45:40,059 - INFO - tty.usbmodem0006822145041: DevkeyAdd: {'devkey_handle': 8}
2019-06-25 17:45:40,059 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.__event_handler of <__main__.Manager object at 0x1050d9160>>
2019-06-25 17:45:40,059 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 227, in __event_handler
    if event._opcode == ConfigurationClient._COMPOSITION_DATA_STATUS:
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/mesh/access.py", line 94, in __eq__
    return (self.serialize == other.serialize())
AttributeError: 'int' object has no attribute 'serialize'

2019-06-25 17:45:40,060 - DEBUG - tty.usbmodem0006822145041: RX: 0584a4000000
2019-06-25 17:45:40,060 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: CmdRsp, data: {'opcode': 164, 'status': 0, 'data': bytearray(b'\x00\x00')}}
2019-06-25 17:45:40,060 - INFO - tty.usbmodem0006822145041: AddrPublicationAdd: {'address_handle': 0}
2019-06-25 17:45:40,060 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.__event_handler of <__main__.Manager object at 0x1050d9160>>
2019-06-25 17:45:40,060 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 227, in __event_handler
    if event._opcode == ConfigurationClient._COMPOSITION_DATA_STATUS:
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/mesh/access.py", line 94, in __eq__
    return (self.serialize == other.serialize())
AttributeError: 'int' object has no attribute 'serialize'

2019-06-25 17:45:40,146 - DEBUG - tty.usbmodem0006822145041: RX: 03c20000
2019-06-25 17:45:40,146 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: ProvLinkClosed, data: {'context_id': 0, 'close_reason': 0}}
2019-06-25 17:45:40,146 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.__event_handler of <__main__.Manager object at 0x1050d9160>>
2019-06-25 17:45:40,147 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 227, in __event_handler
    if event._opcode == ConfigurationClient._COMPOSITION_DATA_STATUS:
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/mesh/access.py", line 94, in __eq__
    return (self.serialize == other.serialize())
AttributeError: 'int' object has no attribute 'serialize'

2019-06-25 17:45:40,147 - INFO - tty.usbmodem0006822145041: Provisioning link closed
2019-06-25 17:45:59,828 - DEBUG - tty.usbmodem0006822145041: Writing: 105 bytearray(b'NP<\xd8+\x9b\xd5\xf3\x12\xd5+\x94\x96\xcf\x04\x03\x80*\xc7\x9a\x8d(\x1d\xee$\x87t\xcd\\U\x87\xacq\xea\xb8Y#\x08\xa9\xfd\xea\xe9\xf3\xf1\xd0\xfbU\xb9\xbfi\xa3\x93\xda>Eo.\xec\xbf\x17\x86\x13r\xbc\xa5}\xfbj\x1b-2j\x912Og\x9b\x08\x16\xb5d\xb3\x87\xc2\xf2\xe0r\xe0\xea\xf7\x7f2\xc4\x0b\x80l')
2019-06-25 17:45:59,830 - DEBUG - tty.usbmodem0006822145041: TX: 61694e503cd82b9bd5f312d52b9496cf0403802ac79a8d281dee248774cd5c5587ac71eab8592308a9fdeae9f3f1d0fb55b9bf69a393da3e456f2eecbf17861372bca57dfb6a1b2d326a91324f679b0816b564b387c2f2e072e0eaf77f32c40b806c
2019-06-25 17:45:59,840 - DEBUG - tty.usbmodem0006822145041: RX: 03845384
2019-06-25 17:45:59,841 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: CmdRsp, data: {'opcode': 83, 'status': 132, 'data': bytearray(b'')}}
2019-06-25 17:45:59,841 - ERROR - tty.usbmodem0006822145041: None: ERROR_INVALID_LENGTH
2019-06-25 17:45:59,841 - DEBUG - tty.usbmodem0006822145041: Writing: 159 bytearray(b'\x01\x00\x01\x00')
2019-06-25 17:45:59,841 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.__event_handler of <__main__.Manager object at 0x105d00400>>
2019-06-25 17:45:59,841 - DEBUG - tty.usbmodem0006822145041: TX: 059f01000100
2019-06-25 17:45:59,842 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 227, in __event_handler
    if event._opcode == ConfigurationClient._COMPOSITION_DATA_STATUS:
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/mesh/access.py", line 94, in __eq__
    return (self.serialize == other.serialize())
AttributeError: 'int' object has no attribute 'serialize'

2019-06-25 17:45:59,843 - DEBUG - tty.usbmodem0006822145041: RX: 03840084
2019-06-25 17:45:59,844 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: CmdRsp, data: {'opcode': 0, 'status': 132, 'data': bytearray(b'')}}
2019-06-25 17:45:59,845 - ERROR - tty.usbmodem0006822145041: None: ERROR_INVALID_LENGTH
2019-06-25 17:45:59,845 - DEBUG - tty.usbmodem0006822145041: Writing: 146 bytearray(b'\x00\x00\x18\xee\xd9\xc2\xa5j\xdd\x85\x04\x9f\xfc<Y\xad\x0e\x12')
2019-06-25 17:45:59,845 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.__event_handler of <__main__.Manager object at 0x105d00400>>
2019-06-25 17:45:59,846 - DEBUG - tty.usbmodem0006822145041: TX: 1392000018eed9c2a56add85049ffc3c59ad0e12
2019-06-25 17:45:59,846 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 227, in __event_handler
    if event._opcode == ConfigurationClient._COMPOSITION_DATA_STATUS:
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/mesh/access.py", line 94, in __eq__
    return (self.serialize == other.serialize())
AttributeError: 'int' object has no attribute 'serialize'

2019-06-25 17:45:59,847 - DEBUG - tty.usbmodem0006822145041: RX: 03840084
2019-06-25 17:45:59,847 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: CmdRsp, data: {'opcode': 0, 'status': 132, 'data': bytearray(b'')}}
2019-06-25 17:45:59,847 - ERROR - tty.usbmodem0006822145041: None: ERROR_INVALID_LENGTH
2019-06-25 17:45:59,847 - DEBUG - tty.usbmodem0006822145041: Writing: 151 bytearray(b'\x00\x00\x00\x00Oh\xad\x85\xd9\xf4\x8a\xc8X\x9d\xf6e\xb6\xb4\x9b\x8a')
2019-06-25 17:45:59,848 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.__event_handler of <__main__.Manager object at 0x105d00400>>
2019-06-25 17:45:59,848 - DEBUG - tty.usbmodem0006822145041: TX: 1597000000004f68ad85d9f48ac8589df665b6b49b8a
2019-06-25 17:45:59,849 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 227, in __event_handler
    if event._opcode == ConfigurationClient._COMPOSITION_DATA_STATUS:
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/mesh/access.py", line 94, in __eq__
    return (self.serialize == other.serialize())
AttributeError: 'int' object has no attribute 'serialize'

2019-06-25 17:45:59,850 - DEBUG - tty.usbmodem0006822145041: RX: 03840084
2019-06-25 17:45:59,850 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: CmdRsp, data: {'opcode': 0, 'status': 132, 'data': bytearray(b'')}}
2019-06-25 17:45:59,850 - ERROR - tty.usbmodem0006822145041: None: ERROR_INVALID_LENGTH
2019-06-25 17:45:59,851 - DEBUG - tty.usbmodem0006822145041: Writing: 151 bytearray(b'\x01\x00\x00\x00*\xa2\xa6\xde\xd5\xa0y\x8c\xea\xb5x|\xa3\xae9\xfc')
2019-06-25 17:45:59,851 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.__event_handler of <__main__.Manager object at 0x105d00400>>
2019-06-25 17:45:59,851 - DEBUG - tty.usbmodem0006822145041: TX: 1597010000002aa2a6ded5a0798ceab5787ca3ae39fc
2019-06-25 17:45:59,852 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 227, in __event_handler
    if event._opcode == ConfigurationClient._COMPOSITION_DATA_STATUS:
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/mesh/access.py", line 94, in __eq__
    return (self.serialize == other.serialize())
AttributeError: 'int' object has no attribute 'serialize'

2019-06-25 17:45:59,852 - DEBUG - tty.usbmodem0006822145041: RX: 03840084
2019-06-25 17:45:59,852 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: CmdRsp, data: {'opcode': 0, 'status': 132, 'data': bytearray(b'')}}
2019-06-25 17:45:59,852 - ERROR - tty.usbmodem0006822145041: None: ERROR_INVALID_LENGTH
2019-06-25 17:45:59,852 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.__event_handler of <__main__.Manager object at 0x105d00400>>
2019-06-25 17:45:59,853 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 227, in __event_handler
    if event._opcode == ConfigurationClient._COMPOSITION_DATA_STATUS:
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/mesh/access.py", line 94, in __eq__
    return (self.serialize == other.serialize())
AttributeError: 'int' object has no attribute 'serialize'

2019-06-25 17:45:59,853 - DEBUG - tty.usbmodem0006822145041: RX: 03840084
2019-06-25 17:45:59,853 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: CmdRsp, data: {'opcode': 0, 'status': 132, 'data': bytearray(b'')}}
2019-06-25 17:45:59,854 - ERROR - tty.usbmodem0006822145041: None: ERROR_INVALID_LENGTH
2019-06-25 17:45:59,854 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.__event_handler of <__main__.Manager object at 0x105d00400>>
2019-06-25 17:45:59,854 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 227, in __event_handler
    if event._opcode == ConfigurationClient._COMPOSITION_DATA_STATUS:
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/mesh/access.py", line 94, in __eq__
    return (self.serialize == other.serialize())
AttributeError: 'int' object has no attribute 'serialize'

2019-06-25 17:45:59,854 - DEBUG - tty.usbmodem0006822145041: RX: 03840084
2019-06-25 17:45:59,854 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: CmdRsp, data: {'opcode': 0, 'status': 132, 'data': bytearray(b'')}}
2019-06-25 17:45:59,855 - ERROR - tty.usbmodem0006822145041: None: ERROR_INVALID_LENGTH
2019-06-25 17:45:59,855 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.__event_handler of <__main__.Manager object at 0x105d00400>>
2019-06-25 17:45:59,855 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 227, in __event_handler
    if event._opcode == ConfigurationClient._COMPOSITION_DATA_STATUS:
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/mesh/access.py", line 94, in __eq__
    return (self.serialize == other.serialize())
AttributeError: 'int' object has no attribute 'serialize'

2019-06-25 17:45:59,856 - DEBUG - tty.usbmodem0006822145041: RX: 03840084
2019-06-25 17:45:59,856 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: CmdRsp, data: {'opcode': 0, 'status': 132, 'data': bytearray(b'')}}
2019-06-25 17:45:59,856 - ERROR - tty.usbmodem0006822145041: None: ERROR_INVALID_LENGTH
2019-06-25 17:45:59,856 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.__event_handler of <__main__.Manager object at 0x105d00400>>
2019-06-25 17:45:59,857 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 227, in __event_handler
    if event._opcode == ConfigurationClient._COMPOSITION_DATA_STATUS:
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/mesh/access.py", line 94, in __eq__
    return (self.serialize == other.serialize())
AttributeError: 'int' object has no attribute 'serialize'

2019-06-25 17:45:59,857 - DEBUG - tty.usbmodem0006822145041: RX: 03840084
2019-06-25 17:45:59,857 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: CmdRsp, data: {'opcode': 0, 'status': 132, 'data': bytearray(b'')}}
2019-06-25 17:45:59,857 - ERROR - tty.usbmodem0006822145041: None: ERROR_INVALID_LENGTH
2019-06-25 17:45:59,857 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.__event_handler of <__main__.Manager object at 0x105d00400>>
2019-06-25 17:45:59,858 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 227, in __event_handler
    if event._opcode == ConfigurationClient._COMPOSITION_DATA_STATUS:
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/mesh/access.py", line 94, in __eq__
    return (self.serialize == other.serialize())
AttributeError: 'int' object has no attribute 'serialize'

2019-06-25 17:45:59,858 - DEBUG - tty.usbmodem0006822145041: RX: 03840084
2019-06-25 17:45:59,858 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: CmdRsp, data: {'opcode': 0, 'status': 132, 'data': bytearray(b'')}}
2019-06-25 17:45:59,858 - ERROR - tty.usbmodem0006822145041: None: ERROR_INVALID_LENGTH
2019-06-25 17:45:59,858 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.__event_handler of <__main__.Manager object at 0x105d00400>>
2019-06-25 17:45:59,858 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 227, in __event_handler
    if event._opcode == ConfigurationClient._COMPOSITION_DATA_STATUS:
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/mesh/access.py", line 94, in __eq__
    return (self.serialize == other.serialize())
AttributeError: 'int' object has no attribute 'serialize'

2019-06-25 17:45:59,859 - DEBUG - tty.usbmodem0006822145041: RX: 03840084
2019-06-25 17:45:59,859 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: CmdRsp, data: {'opcode': 0, 'status': 132, 'data': bytearray(b'')}}
2019-06-25 17:45:59,859 - ERROR - tty.usbmodem0006822145041: None: ERROR_INVALID_LENGTH
2019-06-25 17:45:59,859 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.__event_handler of <__main__.Manager object at 0x105d00400>>
2019-06-25 17:45:59,860 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 227, in __event_handler
    if event._opcode == ConfigurationClient._COMPOSITION_DATA_STATUS:
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/mesh/access.py", line 94, in __eq__
    return (self.serialize == other.serialize())
AttributeError: 'int' object has no attribute 'serialize'

2019-06-25 17:45:59,860 - DEBUG - tty.usbmodem0006822145041: RX: 03840084
2019-06-25 17:45:59,861 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: CmdRsp, data: {'opcode': 0, 'status': 132, 'data': bytearray(b'')}}
2019-06-25 17:45:59,861 - ERROR - tty.usbmodem0006822145041: None: ERROR_INVALID_LENGTH
2019-06-25 17:45:59,861 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.__event_handler of <__main__.Manager object at 0x105d00400>>
2019-06-25 17:45:59,862 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 227, in __event_handler
    if event._opcode == ConfigurationClient._COMPOSITION_DATA_STATUS:
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/mesh/access.py", line 94, in __eq__
    return (self.serialize == other.serialize())
AttributeError: 'int' object has no attribute 'serialize'

2019-06-25 17:45:59,863 - DEBUG - tty.usbmodem0006822145041: RX: 03840084
2019-06-25 17:45:59,863 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: CmdRsp, data: {'opcode': 0, 'status': 132, 'data': bytearray(b'')}}
2019-06-25 17:45:59,865 - ERROR - tty.usbmodem0006822145041: None: ERROR_INVALID_LENGTH
2019-06-25 17:45:59,866 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.__event_handler of <__main__.Manager object at 0x105d00400>>
2019-06-25 17:45:59,867 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 227, in __event_handler
    if event._opcode == ConfigurationClient._COMPOSITION_DATA_STATUS:
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/mesh/access.py", line 94, in __eq__
    return (self.serialize == other.serialize())
AttributeError: 'int' object has no attribute 'serialize'

2019-06-25 17:45:59,868 - DEBUG - tty.usbmodem0006822145041: RX: 03849f8e
2019-06-25 17:45:59,868 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: CmdRsp, data: {'opcode': 159, 'status': 142, 'data': bytearray(b'')}}
2019-06-25 17:45:59,868 - ERROR - tty.usbmodem0006822145041: None: ERROR_REJECTED
2019-06-25 17:45:59,868 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.__event_handler of <__main__.Manager object at 0x105d00400>>
2019-06-25 17:45:59,868 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 227, in __event_handler
    if event._opcode == ConfigurationClient._COMPOSITION_DATA_STATUS:
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/mesh/access.py", line 94, in __eq__
    return (self.serialize == other.serialize())
AttributeError: 'int' object has no attribute 'serialize'

2019-06-25 17:45:59,868 - DEBUG - tty.usbmodem0006822145041: RX: 03849281
2019-06-25 17:45:59,869 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: CmdRsp, data: {'opcode': 146, 'status': 129, 'data': bytearray(b'')}}
2019-06-25 17:45:59,869 - ERROR - tty.usbmodem0006822145041: SubnetAdd: ERROR_INTERNAL
2019-06-25 17:45:59,869 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.__event_handler of <__main__.Manager object at 0x105d00400>>
2019-06-25 17:45:59,869 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 227, in __event_handler
    if event._opcode == ConfigurationClient._COMPOSITION_DATA_STATUS:
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/mesh/access.py", line 94, in __eq__
    return (self.serialize == other.serialize())
AttributeError: 'int' object has no attribute 'serialize'

2019-06-25 17:45:59,870 - DEBUG - tty.usbmodem0006822145041: RX: 03849781
2019-06-25 17:45:59,870 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: CmdRsp, data: {'opcode': 151, 'status': 129, 'data': bytearray(b'')}}
2019-06-25 17:45:59,870 - ERROR - tty.usbmodem0006822145041: AppkeyAdd: ERROR_INTERNAL
2019-06-25 17:45:59,870 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.__event_handler of <__main__.Manager object at 0x105d00400>>
2019-06-25 17:45:59,871 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 227, in __event_handler
    if event._opcode == ConfigurationClient._COMPOSITION_DATA_STATUS:
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/mesh/access.py", line 94, in __eq__
    return (self.serialize == other.serialize())
AttributeError: 'int' object has no attribute 'serialize'

2019-06-25 17:45:59,871 - DEBUG - tty.usbmodem0006822145041: RX: 03849781
2019-06-25 17:45:59,871 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: CmdRsp, data: {'opcode': 151, 'status': 129, 'data': bytearray(b'')}}
2019-06-25 17:45:59,871 - ERROR - tty.usbmodem0006822145041: AppkeyAdd: ERROR_INTERNAL
2019-06-25 17:45:59,871 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.__event_handler of <__main__.Manager object at 0x105d00400>>
2019-06-25 17:45:59,872 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 227, in __event_handler
    if event._opcode == ConfigurationClient._COMPOSITION_DATA_STATUS:
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/mesh/access.py", line 94, in __eq__
    return (self.serialize == other.serialize())
AttributeError: 'int' object has no attribute 'serialize'

2019-06-25 17:46:00,536 - DEBUG - tty.usbmodem0006822145041: Writing: 97 bytearray(b'')
2019-06-25 17:46:00,536 - DEBUG - tty.usbmodem0006822145041: TX: 0161
2019-06-25 17:46:00,537 - DEBUG - tty.usbmodem0006822145041: RX: 03846100
2019-06-25 17:46:00,538 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: CmdRsp, data: {'opcode': 97, 'status': 0, 'data': bytearray(b'')}}
2019-06-25 17:46:00,538 - INFO - tty.usbmodem0006822145041: Success
2019-06-25 17:46:00,538 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.__event_handler of <__main__.Manager object at 0x105d00400>>
2019-06-25 17:46:00,538 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 227, in __event_handler
    if event._opcode == ConfigurationClient._COMPOSITION_DATA_STATUS:
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/mesh/access.py", line 94, in __eq__
    return (self.serialize == other.serialize())
AttributeError: 'int' object has no attribute 'serialize'

