2019-06-25 17:54:37,610 - DEBUG - tty.usbmodem0006822145041: Writing: 105 bytearray(b"\xab\xf6\xbc\xcb\x80\x9c\xddXo\xd1\x81,\xc9)\xbe\x98\x9f\xe0U\xdb\xe2,d7\xf6\xa2\x85\xf4B\xff\xba\xf2]\x91hJq_\xf6\'J\xfa%\xb6|$\xf0#\xb8\xa4\x89\xee\'BU\x0c\xc1\xb3\xe2)\xde\x1c\xbc\x9b\xa5\xef\xd4xQ\x10\xed;Ty\x1dv\xbe\x8e\x92\x83\xd9\x9f\xc9\xa6\xd0\xe1-\x16j\x86\x04\xd0\xac\xf3\xa64")
2019-06-25 17:54:37,611 - DEBUG - tty.usbmodem0006822145041: TX: 6169abf6bccb809cdd586fd1812cc929be989fe055dbe22c6437f6a285f442ffbaf25d91684a715ff6274afa25b67c24f023b8a489ee2742550cc1b3e229de1cbc9ba5efd4785110ed3b54791d76be8e9283d99fc9a6d0e12d166a8604d0acf3a634
2019-06-25 17:54:37,621 - DEBUG - tty.usbmodem0006822145041: RX: 03845384
2019-06-25 17:54:37,622 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: CmdRsp, data: {'opcode': 83, 'status': 132, 'data': bytearray(b'')}}
2019-06-25 17:54:37,624 - ERROR - tty.usbmodem0006822145041: None: ERROR_INVALID_LENGTH
2019-06-25 17:54:37,625 - DEBUG - tty.usbmodem0006822145041: Writing: 159 bytearray(b'\x01\x00\x01\x00')
2019-06-25 17:54:37,626 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.__event_handler of <__main__.Manager object at 0x112d13400>>
2019-06-25 17:54:37,627 - DEBUG - tty.usbmodem0006822145041: TX: 059f01000100
2019-06-25 17:54:37,630 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "./interactive_pyaci.py", line 227, in __event_handler
    if event._opcode == ConfigurationClient._COMPOSITION_DATA_STATUS:
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/mesh/access.py", line 94, in __eq__
    return (self.serialize == other.serialize())
AttributeError: 'int' object has no attribute 'serialize'

2019-06-25 17:54:37,635 - DEBUG - tty.usbmodem0006822145041: RX: 03840084
2019-06-25 17:54:37,635 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: CmdRsp, data: {'opcode': 0, 'status': 132, 'data': bytearray(b'')}}
2019-06-25 17:54:37,635 - ERROR - tty.usbmodem0006822145041: None: ERROR_INVALID_LENGTH
2019-06-25 17:54:37,636 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.__event_handler of <__main__.Manager object at 0x112d13400>>
2019-06-25 17:54:37,638 - DEBUG - tty.usbmodem0006822145041: Writing: 146 bytearray(b'\x00\x00\x18\xee\xd9\xc2\xa5j\xdd\x85\x04\x9f\xfc<Y\xad\x0e\x12')
2019-06-25 17:54:37,640 - DEBUG - tty.usbmodem0006822145041: TX: 1392000018eed9c2a56add85049ffc3c59ad0e12
2019-06-25 17:54:37,645 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "./interactive_pyaci.py", line 227, in __event_handler
    if event._opcode == ConfigurationClient._COMPOSITION_DATA_STATUS:
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/mesh/access.py", line 94, in __eq__
    return (self.serialize == other.serialize())
AttributeError: 'int' object has no attribute 'serialize'

2019-06-25 17:54:37,648 - DEBUG - tty.usbmodem0006822145041: RX: 03840084
2019-06-25 17:54:37,649 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: CmdRsp, data: {'opcode': 0, 'status': 132, 'data': bytearray(b'')}}
2019-06-25 17:54:37,650 - ERROR - tty.usbmodem0006822145041: None: ERROR_INVALID_LENGTH
2019-06-25 17:54:37,650 - DEBUG - tty.usbmodem0006822145041: Writing: 151 bytearray(b'\x00\x00\x00\x00Oh\xad\x85\xd9\xf4\x8a\xc8X\x9d\xf6e\xb6\xb4\x9b\x8a')
2019-06-25 17:54:37,656 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.__event_handler of <__main__.Manager object at 0x112d13400>>
2019-06-25 17:54:37,657 - DEBUG - tty.usbmodem0006822145041: TX: 1597000000004f68ad85d9f48ac8589df665b6b49b8a
2019-06-25 17:54:37,657 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "./interactive_pyaci.py", line 227, in __event_handler
    if event._opcode == ConfigurationClient._COMPOSITION_DATA_STATUS:
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/mesh/access.py", line 94, in __eq__
    return (self.serialize == other.serialize())
AttributeError: 'int' object has no attribute 'serialize'

2019-06-25 17:54:37,658 - DEBUG - tty.usbmodem0006822145041: RX: 03840084
2019-06-25 17:54:37,658 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: CmdRsp, data: {'opcode': 0, 'status': 132, 'data': bytearray(b'')}}
2019-06-25 17:54:37,659 - ERROR - tty.usbmodem0006822145041: None: ERROR_INVALID_LENGTH
2019-06-25 17:54:37,660 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.__event_handler of <__main__.Manager object at 0x112d13400>>
2019-06-25 17:54:37,662 - DEBUG - tty.usbmodem0006822145041: Writing: 151 bytearray(b'\x01\x00\x00\x00*\xa2\xa6\xde\xd5\xa0y\x8c\xea\xb5x|\xa3\xae9\xfc')
2019-06-25 17:54:37,671 - DEBUG - tty.usbmodem0006822145041: TX: 1597010000002aa2a6ded5a0798ceab5787ca3ae39fc
2019-06-25 17:54:37,673 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "./interactive_pyaci.py", line 227, in __event_handler
    if event._opcode == ConfigurationClient._COMPOSITION_DATA_STATUS:
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/mesh/access.py", line 94, in __eq__
    return (self.serialize == other.serialize())
AttributeError: 'int' object has no attribute 'serialize'

2019-06-25 17:54:37,679 - DEBUG - tty.usbmodem0006822145041: RX: 03840084
2019-06-25 17:54:37,680 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: CmdRsp, data: {'opcode': 0, 'status': 132, 'data': bytearray(b'')}}
2019-06-25 17:54:37,682 - ERROR - tty.usbmodem0006822145041: None: ERROR_INVALID_LENGTH
2019-06-25 17:54:37,683 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.__event_handler of <__main__.Manager object at 0x112d13400>>
2019-06-25 17:54:37,684 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "./interactive_pyaci.py", line 227, in __event_handler
    if event._opcode == ConfigurationClient._COMPOSITION_DATA_STATUS:
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/mesh/access.py", line 94, in __eq__
    return (self.serialize == other.serialize())
AttributeError: 'int' object has no attribute 'serialize'

2019-06-25 17:54:37,691 - DEBUG - tty.usbmodem0006822145041: RX: 03840084
2019-06-25 17:54:37,691 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: CmdRsp, data: {'opcode': 0, 'status': 132, 'data': bytearray(b'')}}
2019-06-25 17:54:37,692 - ERROR - tty.usbmodem0006822145041: None: ERROR_INVALID_LENGTH
2019-06-25 17:54:37,692 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.__event_handler of <__main__.Manager object at 0x112d13400>>
2019-06-25 17:54:37,692 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "./interactive_pyaci.py", line 227, in __event_handler
    if event._opcode == ConfigurationClient._COMPOSITION_DATA_STATUS:
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/mesh/access.py", line 94, in __eq__
    return (self.serialize == other.serialize())
AttributeError: 'int' object has no attribute 'serialize'

2019-06-25 17:54:37,693 - DEBUG - tty.usbmodem0006822145041: RX: 03840084
2019-06-25 17:54:37,693 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: CmdRsp, data: {'opcode': 0, 'status': 132, 'data': bytearray(b'')}}
2019-06-25 17:54:37,693 - ERROR - tty.usbmodem0006822145041: None: ERROR_INVALID_LENGTH
2019-06-25 17:54:37,694 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.__event_handler of <__main__.Manager object at 0x112d13400>>
2019-06-25 17:54:37,694 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "./interactive_pyaci.py", line 227, in __event_handler
    if event._opcode == ConfigurationClient._COMPOSITION_DATA_STATUS:
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/mesh/access.py", line 94, in __eq__
    return (self.serialize == other.serialize())
AttributeError: 'int' object has no attribute 'serialize'

2019-06-25 17:54:37,704 - DEBUG - tty.usbmodem0006822145041: RX: 03840084
2019-06-25 17:54:37,705 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: CmdRsp, data: {'opcode': 0, 'status': 132, 'data': bytearray(b'')}}
2019-06-25 17:54:37,705 - ERROR - tty.usbmodem0006822145041: None: ERROR_INVALID_LENGTH
2019-06-25 17:54:37,705 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.__event_handler of <__main__.Manager object at 0x112d13400>>
2019-06-25 17:54:37,706 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "./interactive_pyaci.py", line 227, in __event_handler
    if event._opcode == ConfigurationClient._COMPOSITION_DATA_STATUS:
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/mesh/access.py", line 94, in __eq__
    return (self.serialize == other.serialize())
AttributeError: 'int' object has no attribute 'serialize'

2019-06-25 17:54:37,708 - DEBUG - tty.usbmodem0006822145041: RX: 03840084
2019-06-25 17:54:37,709 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: CmdRsp, data: {'opcode': 0, 'status': 132, 'data': bytearray(b'')}}
2019-06-25 17:54:37,711 - ERROR - tty.usbmodem0006822145041: None: ERROR_INVALID_LENGTH
2019-06-25 17:54:37,714 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.__event_handler of <__main__.Manager object at 0x112d13400>>
2019-06-25 17:54:37,715 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "./interactive_pyaci.py", line 227, in __event_handler
    if event._opcode == ConfigurationClient._COMPOSITION_DATA_STATUS:
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/mesh/access.py", line 94, in __eq__
    return (self.serialize == other.serialize())
AttributeError: 'int' object has no attribute 'serialize'

2019-06-25 17:54:37,718 - DEBUG - tty.usbmodem0006822145041: RX: 03840084
2019-06-25 17:54:37,719 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: CmdRsp, data: {'opcode': 0, 'status': 132, 'data': bytearray(b'')}}
2019-06-25 17:54:37,720 - ERROR - tty.usbmodem0006822145041: None: ERROR_INVALID_LENGTH
2019-06-25 17:54:37,720 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.__event_handler of <__main__.Manager object at 0x112d13400>>
2019-06-25 17:54:37,720 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "./interactive_pyaci.py", line 227, in __event_handler
    if event._opcode == ConfigurationClient._COMPOSITION_DATA_STATUS:
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/mesh/access.py", line 94, in __eq__
    return (self.serialize == other.serialize())
AttributeError: 'int' object has no attribute 'serialize'

2019-06-25 17:54:37,735 - DEBUG - tty.usbmodem0006822145041: RX: 03840084
2019-06-25 17:54:37,735 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: CmdRsp, data: {'opcode': 0, 'status': 132, 'data': bytearray(b'')}}
2019-06-25 17:54:37,735 - ERROR - tty.usbmodem0006822145041: None: ERROR_INVALID_LENGTH
2019-06-25 17:54:37,735 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.__event_handler of <__main__.Manager object at 0x112d13400>>
2019-06-25 17:54:37,736 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "./interactive_pyaci.py", line 227, in __event_handler
    if event._opcode == ConfigurationClient._COMPOSITION_DATA_STATUS:
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/mesh/access.py", line 94, in __eq__
    return (self.serialize == other.serialize())
AttributeError: 'int' object has no attribute 'serialize'

2019-06-25 17:54:37,737 - DEBUG - tty.usbmodem0006822145041: RX: 03840084
2019-06-25 17:54:37,738 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: CmdRsp, data: {'opcode': 0, 'status': 132, 'data': bytearray(b'')}}
2019-06-25 17:54:37,738 - ERROR - tty.usbmodem0006822145041: None: ERROR_INVALID_LENGTH
2019-06-25 17:54:37,740 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.__event_handler of <__main__.Manager object at 0x112d13400>>
2019-06-25 17:54:37,745 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "./interactive_pyaci.py", line 227, in __event_handler
    if event._opcode == ConfigurationClient._COMPOSITION_DATA_STATUS:
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/mesh/access.py", line 94, in __eq__
    return (self.serialize == other.serialize())
AttributeError: 'int' object has no attribute 'serialize'

2019-06-25 17:54:37,756 - DEBUG - tty.usbmodem0006822145041: RX: 03840084
2019-06-25 17:54:37,757 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: CmdRsp, data: {'opcode': 0, 'status': 132, 'data': bytearray(b'')}}
2019-06-25 17:54:37,757 - ERROR - tty.usbmodem0006822145041: None: ERROR_INVALID_LENGTH
2019-06-25 17:54:37,757 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.__event_handler of <__main__.Manager object at 0x112d13400>>
2019-06-25 17:54:37,757 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "./interactive_pyaci.py", line 227, in __event_handler
    if event._opcode == ConfigurationClient._COMPOSITION_DATA_STATUS:
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/mesh/access.py", line 94, in __eq__
    return (self.serialize == other.serialize())
AttributeError: 'int' object has no attribute 'serialize'

2019-06-25 17:54:37,758 - DEBUG - tty.usbmodem0006822145041: RX: 03849f8e
2019-06-25 17:54:37,758 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: CmdRsp, data: {'opcode': 159, 'status': 142, 'data': bytearray(b'')}}
2019-06-25 17:54:37,770 - ERROR - tty.usbmodem0006822145041: None: ERROR_REJECTED
2019-06-25 17:54:37,771 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.__event_handler of <__main__.Manager object at 0x112d13400>>
2019-06-25 17:54:37,774 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "./interactive_pyaci.py", line 227, in __event_handler
    if event._opcode == ConfigurationClient._COMPOSITION_DATA_STATUS:
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/mesh/access.py", line 94, in __eq__
    return (self.serialize == other.serialize())
AttributeError: 'int' object has no attribute 'serialize'

2019-06-25 17:54:37,777 - DEBUG - tty.usbmodem0006822145041: RX: 03849281
2019-06-25 17:54:37,778 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: CmdRsp, data: {'opcode': 146, 'status': 129, 'data': bytearray(b'')}}
2019-06-25 17:54:37,790 - ERROR - tty.usbmodem0006822145041: SubnetAdd: ERROR_INTERNAL
2019-06-25 17:54:37,790 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.__event_handler of <__main__.Manager object at 0x112d13400>>
2019-06-25 17:54:37,790 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "./interactive_pyaci.py", line 227, in __event_handler
    if event._opcode == ConfigurationClient._COMPOSITION_DATA_STATUS:
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/mesh/access.py", line 94, in __eq__
    return (self.serialize == other.serialize())
AttributeError: 'int' object has no attribute 'serialize'

2019-06-25 17:54:37,791 - DEBUG - tty.usbmodem0006822145041: RX: 03849781
2019-06-25 17:54:37,791 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: CmdRsp, data: {'opcode': 151, 'status': 129, 'data': bytearray(b'')}}
2019-06-25 17:54:37,791 - ERROR - tty.usbmodem0006822145041: AppkeyAdd: ERROR_INTERNAL
2019-06-25 17:54:37,791 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.__event_handler of <__main__.Manager object at 0x112d13400>>
2019-06-25 17:54:37,793 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "./interactive_pyaci.py", line 227, in __event_handler
    if event._opcode == ConfigurationClient._COMPOSITION_DATA_STATUS:
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/mesh/access.py", line 94, in __eq__
    return (self.serialize == other.serialize())
AttributeError: 'int' object has no attribute 'serialize'

2019-06-25 17:54:37,807 - DEBUG - tty.usbmodem0006822145041: RX: 03849781
2019-06-25 17:54:37,809 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: CmdRsp, data: {'opcode': 151, 'status': 129, 'data': bytearray(b'')}}
2019-06-25 17:54:37,811 - ERROR - tty.usbmodem0006822145041: AppkeyAdd: ERROR_INTERNAL
2019-06-25 17:54:37,812 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.__event_handler of <__main__.Manager object at 0x112d13400>>
2019-06-25 17:54:37,813 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "./interactive_pyaci.py", line 227, in __event_handler
    if event._opcode == ConfigurationClient._COMPOSITION_DATA_STATUS:
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/mesh/access.py", line 94, in __eq__
    return (self.serialize == other.serialize())
AttributeError: 'int' object has no attribute 'serialize'

