2019-06-25 17:47:07,761 - DEBUG - tty.usbmodem0006822145041: Writing: 105 bytearray(b'\x9dH\x12\xd95\x9c\nV\x05\xef\xd4\x1eWe\x0bw\xe3C\x81\xb6K1\xe4\xc5\xe6<_i\x8fEu`b#:\x9e\xc82Rt\xb4\x82L\x1e\xc2\xfa\x05\x8f\xc5F\xf0\xf2\xd9\xaera\x89^\xd6\xc3\x81\xe8b\x9b \x908\xe1\x1cit#49\xcf%\x1c\xbaX\r\x16G\xf0\x83?|)\xfd\xd8\xff\x12\xd4\\S\x10\xcc')
2019-06-25 17:47:07,761 - DEBUG - tty.usbmodem0006822145041: TX: 61699d4812d9359c0a5605efd41e57650b77e34381b64b31e4c5e63c5f698f45756062233a9ec8325274b4824c1ec2fa058fc546f0f2d9ae7261895ed6c381e8629b209038e11c6974233439cf251cba580d1647f0833f7c29fdd8ff12d45c5310cc
2019-06-25 17:47:07,771 - DEBUG - tty.usbmodem0006822145041: RX: 03845384
2019-06-25 17:47:07,771 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: CmdRsp, data: {'opcode': 83, 'status': 132, 'data': bytearray(b'')}}
2019-06-25 17:47:07,771 - ERROR - tty.usbmodem0006822145041: None: ERROR_INVALID_LENGTH
2019-06-25 17:47:07,771 - DEBUG - tty.usbmodem0006822145041: Writing: 159 bytearray(b'\x01\x00\x01\x00')
2019-06-25 17:47:07,771 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.__event_handler of <__main__.Manager object at 0x103d562b0>>
2019-06-25 17:47:07,772 - DEBUG - tty.usbmodem0006822145041: TX: 059f01000100
2019-06-25 17:47:07,776 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 227, in __event_handler
    if event._opcode == ConfigurationClient._COMPOSITION_DATA_STATUS:
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/mesh/access.py", line 94, in __eq__
    return (self.serialize == other.serialize())
AttributeError: 'int' object has no attribute 'serialize'

2019-06-25 17:47:07,777 - DEBUG - tty.usbmodem0006822145041: RX: 03840084
2019-06-25 17:47:07,777 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: CmdRsp, data: {'opcode': 0, 'status': 132, 'data': bytearray(b'')}}
2019-06-25 17:47:07,777 - ERROR - tty.usbmodem0006822145041: None: ERROR_INVALID_LENGTH
2019-06-25 17:47:07,777 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.__event_handler of <__main__.Manager object at 0x103d562b0>>
2019-06-25 17:47:07,777 - DEBUG - tty.usbmodem0006822145041: Writing: 146 bytearray(b'\x00\x00\x18\xee\xd9\xc2\xa5j\xdd\x85\x04\x9f\xfc<Y\xad\x0e\x12')
2019-06-25 17:47:07,777 - DEBUG - tty.usbmodem0006822145041: TX: 1392000018eed9c2a56add85049ffc3c59ad0e12
2019-06-25 17:47:07,778 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 227, in __event_handler
    if event._opcode == ConfigurationClient._COMPOSITION_DATA_STATUS:
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/mesh/access.py", line 94, in __eq__
    return (self.serialize == other.serialize())
AttributeError: 'int' object has no attribute 'serialize'

2019-06-25 17:47:07,778 - DEBUG - tty.usbmodem0006822145041: RX: 03840084
2019-06-25 17:47:07,778 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: CmdRsp, data: {'opcode': 0, 'status': 132, 'data': bytearray(b'')}}
2019-06-25 17:47:07,778 - ERROR - tty.usbmodem0006822145041: None: ERROR_INVALID_LENGTH
2019-06-25 17:47:07,778 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.__event_handler of <__main__.Manager object at 0x103d562b0>>
2019-06-25 17:47:07,778 - DEBUG - tty.usbmodem0006822145041: Writing: 151 bytearray(b'\x00\x00\x00\x00Oh\xad\x85\xd9\xf4\x8a\xc8X\x9d\xf6e\xb6\xb4\x9b\x8a')
2019-06-25 17:47:07,778 - DEBUG - tty.usbmodem0006822145041: TX: 1597000000004f68ad85d9f48ac8589df665b6b49b8a
2019-06-25 17:47:07,778 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 227, in __event_handler
    if event._opcode == ConfigurationClient._COMPOSITION_DATA_STATUS:
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/mesh/access.py", line 94, in __eq__
    return (self.serialize == other.serialize())
AttributeError: 'int' object has no attribute 'serialize'

2019-06-25 17:47:07,779 - DEBUG - tty.usbmodem0006822145041: RX: 03840084
2019-06-25 17:47:07,779 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: CmdRsp, data: {'opcode': 0, 'status': 132, 'data': bytearray(b'')}}
2019-06-25 17:47:07,779 - ERROR - tty.usbmodem0006822145041: None: ERROR_INVALID_LENGTH
2019-06-25 17:47:07,779 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.__event_handler of <__main__.Manager object at 0x103d562b0>>
2019-06-25 17:47:07,779 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 227, in __event_handler
    if event._opcode == ConfigurationClient._COMPOSITION_DATA_STATUS:
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/mesh/access.py", line 94, in __eq__
    return (self.serialize == other.serialize())
AttributeError: 'int' object has no attribute 'serialize'

2019-06-25 17:47:07,779 - DEBUG - tty.usbmodem0006822145041: Writing: 151 bytearray(b'\x01\x00\x00\x00*\xa2\xa6\xde\xd5\xa0y\x8c\xea\xb5x|\xa3\xae9\xfc')
2019-06-25 17:47:07,779 - DEBUG - tty.usbmodem0006822145041: TX: 1597010000002aa2a6ded5a0798ceab5787ca3ae39fc
2019-06-25 17:47:07,780 - DEBUG - tty.usbmodem0006822145041: RX: 03840084
2019-06-25 17:47:07,780 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: CmdRsp, data: {'opcode': 0, 'status': 132, 'data': bytearray(b'')}}
2019-06-25 17:47:07,780 - ERROR - tty.usbmodem0006822145041: None: ERROR_INVALID_LENGTH
2019-06-25 17:47:07,780 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.__event_handler of <__main__.Manager object at 0x103d562b0>>
2019-06-25 17:47:07,780 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 227, in __event_handler
    if event._opcode == ConfigurationClient._COMPOSITION_DATA_STATUS:
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/mesh/access.py", line 94, in __eq__
    return (self.serialize == other.serialize())
AttributeError: 'int' object has no attribute 'serialize'

2019-06-25 17:47:07,780 - DEBUG - tty.usbmodem0006822145041: RX: 03840084
2019-06-25 17:47:07,780 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: CmdRsp, data: {'opcode': 0, 'status': 132, 'data': bytearray(b'')}}
2019-06-25 17:47:07,781 - ERROR - tty.usbmodem0006822145041: None: ERROR_INVALID_LENGTH
2019-06-25 17:47:07,781 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.__event_handler of <__main__.Manager object at 0x103d562b0>>
2019-06-25 17:47:07,781 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 227, in __event_handler
    if event._opcode == ConfigurationClient._COMPOSITION_DATA_STATUS:
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/mesh/access.py", line 94, in __eq__
    return (self.serialize == other.serialize())
AttributeError: 'int' object has no attribute 'serialize'

2019-06-25 17:47:07,781 - DEBUG - tty.usbmodem0006822145041: RX: 03840084
2019-06-25 17:47:07,781 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: CmdRsp, data: {'opcode': 0, 'status': 132, 'data': bytearray(b'')}}
2019-06-25 17:47:07,781 - ERROR - tty.usbmodem0006822145041: None: ERROR_INVALID_LENGTH
2019-06-25 17:47:07,781 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.__event_handler of <__main__.Manager object at 0x103d562b0>>
2019-06-25 17:47:07,781 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 227, in __event_handler
    if event._opcode == ConfigurationClient._COMPOSITION_DATA_STATUS:
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/mesh/access.py", line 94, in __eq__
    return (self.serialize == other.serialize())
AttributeError: 'int' object has no attribute 'serialize'

2019-06-25 17:47:07,781 - DEBUG - tty.usbmodem0006822145041: RX: 03840084
2019-06-25 17:47:07,781 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: CmdRsp, data: {'opcode': 0, 'status': 132, 'data': bytearray(b'')}}
2019-06-25 17:47:07,781 - ERROR - tty.usbmodem0006822145041: None: ERROR_INVALID_LENGTH
2019-06-25 17:47:07,782 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.__event_handler of <__main__.Manager object at 0x103d562b0>>
2019-06-25 17:47:07,782 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 227, in __event_handler
    if event._opcode == ConfigurationClient._COMPOSITION_DATA_STATUS:
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/mesh/access.py", line 94, in __eq__
    return (self.serialize == other.serialize())
AttributeError: 'int' object has no attribute 'serialize'

2019-06-25 17:47:07,782 - DEBUG - tty.usbmodem0006822145041: RX: 03840084
2019-06-25 17:47:07,782 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: CmdRsp, data: {'opcode': 0, 'status': 132, 'data': bytearray(b'')}}
2019-06-25 17:47:07,782 - ERROR - tty.usbmodem0006822145041: None: ERROR_INVALID_LENGTH
2019-06-25 17:47:07,782 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.__event_handler of <__main__.Manager object at 0x103d562b0>>
2019-06-25 17:47:07,782 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 227, in __event_handler
    if event._opcode == ConfigurationClient._COMPOSITION_DATA_STATUS:
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/mesh/access.py", line 94, in __eq__
    return (self.serialize == other.serialize())
AttributeError: 'int' object has no attribute 'serialize'

2019-06-25 17:47:07,782 - DEBUG - tty.usbmodem0006822145041: RX: 03840084
2019-06-25 17:47:07,782 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: CmdRsp, data: {'opcode': 0, 'status': 132, 'data': bytearray(b'')}}
2019-06-25 17:47:07,782 - ERROR - tty.usbmodem0006822145041: None: ERROR_INVALID_LENGTH
2019-06-25 17:47:07,783 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.__event_handler of <__main__.Manager object at 0x103d562b0>>
2019-06-25 17:47:07,783 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 227, in __event_handler
    if event._opcode == ConfigurationClient._COMPOSITION_DATA_STATUS:
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/mesh/access.py", line 94, in __eq__
    return (self.serialize == other.serialize())
AttributeError: 'int' object has no attribute 'serialize'

2019-06-25 17:47:07,783 - DEBUG - tty.usbmodem0006822145041: RX: 03840084
2019-06-25 17:47:07,783 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: CmdRsp, data: {'opcode': 0, 'status': 132, 'data': bytearray(b'')}}
2019-06-25 17:47:07,783 - ERROR - tty.usbmodem0006822145041: None: ERROR_INVALID_LENGTH
2019-06-25 17:47:07,783 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.__event_handler of <__main__.Manager object at 0x103d562b0>>
2019-06-25 17:47:07,783 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 227, in __event_handler
    if event._opcode == ConfigurationClient._COMPOSITION_DATA_STATUS:
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/mesh/access.py", line 94, in __eq__
    return (self.serialize == other.serialize())
AttributeError: 'int' object has no attribute 'serialize'

2019-06-25 17:47:07,783 - DEBUG - tty.usbmodem0006822145041: RX: 03840084
2019-06-25 17:47:07,783 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: CmdRsp, data: {'opcode': 0, 'status': 132, 'data': bytearray(b'')}}
2019-06-25 17:47:07,784 - ERROR - tty.usbmodem0006822145041: None: ERROR_INVALID_LENGTH
2019-06-25 17:47:07,784 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.__event_handler of <__main__.Manager object at 0x103d562b0>>
2019-06-25 17:47:07,784 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 227, in __event_handler
    if event._opcode == ConfigurationClient._COMPOSITION_DATA_STATUS:
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/mesh/access.py", line 94, in __eq__
    return (self.serialize == other.serialize())
AttributeError: 'int' object has no attribute 'serialize'

2019-06-25 17:47:07,784 - DEBUG - tty.usbmodem0006822145041: RX: 03840084
2019-06-25 17:47:07,784 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: CmdRsp, data: {'opcode': 0, 'status': 132, 'data': bytearray(b'')}}
2019-06-25 17:47:07,784 - ERROR - tty.usbmodem0006822145041: None: ERROR_INVALID_LENGTH
2019-06-25 17:47:07,784 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.__event_handler of <__main__.Manager object at 0x103d562b0>>
2019-06-25 17:47:07,784 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 227, in __event_handler
    if event._opcode == ConfigurationClient._COMPOSITION_DATA_STATUS:
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/mesh/access.py", line 94, in __eq__
    return (self.serialize == other.serialize())
AttributeError: 'int' object has no attribute 'serialize'

2019-06-25 17:47:07,784 - DEBUG - tty.usbmodem0006822145041: RX: 03849f00
2019-06-25 17:47:07,784 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: CmdRsp, data: {'opcode': 159, 'status': 0, 'data': bytearray(b'')}}
2019-06-25 17:47:07,784 - INFO - tty.usbmodem0006822145041: Success
2019-06-25 17:47:07,785 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.__event_handler of <__main__.Manager object at 0x103d562b0>>
2019-06-25 17:47:07,785 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 227, in __event_handler
    if event._opcode == ConfigurationClient._COMPOSITION_DATA_STATUS:
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/mesh/access.py", line 94, in __eq__
    return (self.serialize == other.serialize())
AttributeError: 'int' object has no attribute 'serialize'

2019-06-25 17:47:07,785 - DEBUG - tty.usbmodem0006822145041: RX: 058492000000
2019-06-25 17:47:07,785 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: CmdRsp, data: {'opcode': 146, 'status': 0, 'data': bytearray(b'\x00\x00')}}
2019-06-25 17:47:07,785 - INFO - tty.usbmodem0006822145041: SubnetAdd: {'subnet_handle': 0}
2019-06-25 17:47:07,785 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.__event_handler of <__main__.Manager object at 0x103d562b0>>
2019-06-25 17:47:07,785 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 227, in __event_handler
    if event._opcode == ConfigurationClient._COMPOSITION_DATA_STATUS:
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/mesh/access.py", line 94, in __eq__
    return (self.serialize == other.serialize())
AttributeError: 'int' object has no attribute 'serialize'

2019-06-25 17:47:07,785 - DEBUG - tty.usbmodem0006822145041: RX: 058497000000
2019-06-25 17:47:07,785 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: CmdRsp, data: {'opcode': 151, 'status': 0, 'data': bytearray(b'\x00\x00')}}
2019-06-25 17:47:07,786 - INFO - tty.usbmodem0006822145041: AppkeyAdd: {'appkey_handle': 0}
2019-06-25 17:47:07,786 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.__event_handler of <__main__.Manager object at 0x103d562b0>>
2019-06-25 17:47:07,786 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 227, in __event_handler
    if event._opcode == ConfigurationClient._COMPOSITION_DATA_STATUS:
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/mesh/access.py", line 94, in __eq__
    return (self.serialize == other.serialize())
AttributeError: 'int' object has no attribute 'serialize'

2019-06-25 17:47:07,786 - DEBUG - tty.usbmodem0006822145041: RX: 058497000100
2019-06-25 17:47:07,786 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: CmdRsp, data: {'opcode': 151, 'status': 0, 'data': bytearray(b'\x01\x00')}}
2019-06-25 17:47:07,786 - INFO - tty.usbmodem0006822145041: AppkeyAdd: {'appkey_handle': 1}
2019-06-25 17:47:07,786 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.__event_handler of <__main__.Manager object at 0x103d562b0>>
2019-06-25 17:47:07,787 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 227, in __event_handler
    if event._opcode == ConfigurationClient._COMPOSITION_DATA_STATUS:
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/mesh/access.py", line 94, in __eq__
    return (self.serialize == other.serialize())
AttributeError: 'int' object has no attribute 'serialize'

2019-06-25 17:47:08,868 - DEBUG - tty.usbmodem0006822145041: Writing: 97 bytearray(b'')
2019-06-25 17:47:08,868 - DEBUG - tty.usbmodem0006822145041: TX: 0161
2019-06-25 17:47:08,870 - DEBUG - tty.usbmodem0006822145041: RX: 03846100
2019-06-25 17:47:08,870 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: CmdRsp, data: {'opcode': 97, 'status': 0, 'data': bytearray(b'')}}
2019-06-25 17:47:08,871 - INFO - tty.usbmodem0006822145041: Success
2019-06-25 17:47:08,871 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.__event_handler of <__main__.Manager object at 0x103d562b0>>
2019-06-25 17:47:08,871 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 227, in __event_handler
    if event._opcode == ConfigurationClient._COMPOSITION_DATA_STATUS:
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/mesh/access.py", line 94, in __eq__
    return (self.serialize == other.serialize())
AttributeError: 'int' object has no attribute 'serialize'

2019-06-25 17:47:10,048 - DEBUG - tty.usbmodem0006822145041: RX: 1ac09db77a0526b8734988639509c242d107d20001c8639509c2c2
2019-06-25 17:47:10,070 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: ProvUnprovisionedReceived, data: {'uuid': bytearray(b'\x9d\xb7z\x05&\xb8sI\x88c\x95\t\xc2B\xd1\x07'), 'rssi': -46, 'gatt_supported': 0, 'adv_addr_type': 1, 'adv_addr': bytearray(b'\xc8c\x95\t\xc2\xc2')}}
2019-06-25 17:47:10,071 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.__event_handler of <__main__.Manager object at 0x103d562b0>>
2019-06-25 17:47:10,071 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 227, in __event_handler
    if event._opcode == ConfigurationClient._COMPOSITION_DATA_STATUS:
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/mesh/access.py", line 94, in __eq__
    return (self.serialize == other.serialize())
AttributeError: 'int' object has no attribute 'serialize'

2019-06-25 17:47:10,071 - INFO - tty.usbmodem0006822145041: Received UUID 9db77a0526b8734988639509c242d107 with RSSI: -46 dB
2019-06-25 17:47:11,875 - DEBUG - tty.usbmodem0006822145041: Writing: 98 bytearray(b'')
2019-06-25 17:47:11,882 - DEBUG - tty.usbmodem0006822145041: TX: 0162
2019-06-25 17:47:11,900 - DEBUG - tty.usbmodem0006822145041: Writing: 99 bytearray(b'\x00\x9d\xb7z\x05&\xb8sI\x88c\x95\t\xc2B\xd1\x07\x18\xee\xd9\xc2\xa5j\xdd\x85\x04\x9f\xfc<Y\xad\x0e\x12\x00\x00\x00\x00\x00\x00"\x00\x00\x00\x00')
2019-06-25 17:47:11,906 - DEBUG - tty.usbmodem0006822145041: RX: 03846200
2019-06-25 17:47:11,906 - DEBUG - tty.usbmodem0006822145041: TX: 2d63009db77a0526b8734988639509c242d10718eed9c2a56add85049ffc3c59ad0e120000000000002200000000
2019-06-25 17:47:11,924 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: CmdRsp, data: {'opcode': 98, 'status': 0, 'data': bytearray(b'')}}
2019-06-25 17:47:11,952 - INFO - tty.usbmodem0006822145041: Success
2019-06-25 17:47:11,952 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.__event_handler of <__main__.Manager object at 0x103d562b0>>
2019-06-25 17:47:11,964 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 227, in __event_handler
    if event._opcode == ConfigurationClient._COMPOSITION_DATA_STATUS:
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/mesh/access.py", line 94, in __eq__
    return (self.serialize == other.serialize())
AttributeError: 'int' object has no attribute 'serialize'

2019-06-25 17:47:11,970 - DEBUG - tty.usbmodem0006822145041: RX: 0484630000
2019-06-25 17:47:11,970 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: CmdRsp, data: {'opcode': 99, 'status': 0, 'data': bytearray(b'\x00')}}
2019-06-25 17:47:11,970 - INFO - tty.usbmodem0006822145041: Provision: {'context': 0}
2019-06-25 17:47:11,970 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.__event_handler of <__main__.Manager object at 0x103d562b0>>
2019-06-25 17:47:11,976 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 227, in __event_handler
    if event._opcode == ConfigurationClient._COMPOSITION_DATA_STATUS:
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/mesh/access.py", line 94, in __eq__
    return (self.serialize == other.serialize())
AttributeError: 'int' object has no attribute 'serialize'

2019-06-25 17:47:11,987 - DEBUG - tty.usbmodem0006822145041: RX: 02c100
2019-06-25 17:47:11,993 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: ProvLinkEstablished, data: {'context_id': 0}}
2019-06-25 17:47:11,993 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.__event_handler of <__main__.Manager object at 0x103d562b0>>
2019-06-25 17:47:11,998 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 227, in __event_handler
    if event._opcode == ConfigurationClient._COMPOSITION_DATA_STATUS:
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/mesh/access.py", line 94, in __eq__
    return (self.serialize == other.serialize())
AttributeError: 'int' object has no attribute 'serialize'

2019-06-25 17:47:12,004 - INFO - tty.usbmodem0006822145041: Link established
2019-06-25 17:47:12,005 - DEBUG - tty.usbmodem0006822145041.ConfigurationClient: Sending opcode: 8008, data: 00
2019-06-25 17:47:12,006 - DEBUG - tty.usbmodem0006822145041: Writing: 171 bytearray(b'\x08\x00\x01\x00\x00\x00\x08\x00\x00\x00\x80\x08\x00')
2019-06-25 17:47:12,006 - DEBUG - tty.usbmodem0006822145041: TX: 0eab08000100000008000000800800
2019-06-25 17:47:12,009 - DEBUG - tty.usbmodem0006822145041: RX: 0384ab8e
2019-06-25 17:47:12,009 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: CmdRsp, data: {'opcode': 171, 'status': 142, 'data': bytearray(b'')}}
2019-06-25 17:47:12,009 - ERROR - tty.usbmodem0006822145041: PacketSend: ERROR_REJECTED
2019-06-25 17:47:12,009 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.__event_handler of <__main__.Manager object at 0x103d562b0>>
2019-06-25 17:47:12,009 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 227, in __event_handler
    if event._opcode == ConfigurationClient._COMPOSITION_DATA_STATUS:
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/mesh/access.py", line 94, in __eq__
    return (self.serialize == other.serialize())
AttributeError: 'int' object has no attribute 'serialize'

2019-06-25 17:47:18,050 - DEBUG - tty.usbmodem0006822145041: RX: 0bc300010001000000000000
2019-06-25 17:47:18,050 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: ProvCapsReceived, data: {'context_id': 0, 'num_elements': 1, 'public_key_type': 0, 'static_oob_types': 1, 'output_oob_size': 0, 'output_oob_actions': 0, 'input_oob_size': 0, 'input_oob_actions': 0}}
2019-06-25 17:47:18,050 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.__event_handler of <__main__.Manager object at 0x103d562b0>>
2019-06-25 17:47:18,051 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 227, in __event_handler
    if event._opcode == ConfigurationClient._COMPOSITION_DATA_STATUS:
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/mesh/access.py", line 94, in __eq__
    return (self.serialize == other.serialize())
AttributeError: 'int' object has no attribute 'serialize'

2019-06-25 17:47:18,051 - INFO - tty.usbmodem0006822145041: Received capabilities
2019-06-25 17:47:18,051 - INFO - tty.usbmodem0006822145041: Number of elements: 1
2019-06-25 17:47:18,051 - DEBUG - tty.usbmodem0006822145041: Writing: 102 bytearray(b'\x00\x00\x00\x00')
2019-06-25 17:47:18,051 - DEBUG - tty.usbmodem0006822145041: TX: 056600000000
2019-06-25 17:47:18,053 - DEBUG - tty.usbmodem0006822145041: RX: 0484660000
2019-06-25 17:47:18,053 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: CmdRsp, data: {'opcode': 102, 'status': 0, 'data': bytearray(b'\x00')}}
2019-06-25 17:47:18,053 - INFO - tty.usbmodem0006822145041: OobUse: {'context': 0}
2019-06-25 17:47:18,053 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.__event_handler of <__main__.Manager object at 0x103d562b0>>
2019-06-25 17:47:18,054 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 227, in __event_handler
    if event._opcode == ConfigurationClient._COMPOSITION_DATA_STATUS:
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/mesh/access.py", line 94, in __eq__
    return (self.serialize == other.serialize())
AttributeError: 'int' object has no attribute 'serialize'

2019-06-25 17:47:20,293 - DEBUG - tty.usbmodem0006822145041: RX: 62c7001b408ca5d7bb6d9d828acd423f2ebd48f5a5ea1e67e45d7bf4202875aa972ccdeb395c3e6af5750a397d6c02de827d601163193bbfbe4ee4f56ebec45ab85ce9c3d13b45e30b1a65d28df9bdc8bae56fb5c8de72da75868421c83a8b783c9c9f
2019-06-25 17:47:20,293 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: ProvEcdhRequest, data: {'context_id': 0, 'peer_public': bytearray(b'\x1b@\x8c\xa5\xd7\xbbm\x9d\x82\x8a\xcdB?.\xbdH\xf5\xa5\xea\x1eg\xe4]{\xf4 (u\xaa\x97,\xcd\xeb9\\>j\xf5u\n9}l\x02\xde\x82}`\x11c\x19;\xbf\xbeN\xe4\xf5n\xbe\xc4Z\xb8\\\xe9'), 'node_private': bytearray(b'\xc3\xd1;E\xe3\x0b\x1ae\xd2\x8d\xf9\xbd\xc8\xba\xe5o\xb5\xc8\xder\xdau\x86\x84!\xc8:\x8bx<\x9c\x9f')}}
2019-06-25 17:47:20,293 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.__event_handler of <__main__.Manager object at 0x103d562b0>>
2019-06-25 17:47:20,294 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 227, in __event_handler
    if event._opcode == ConfigurationClient._COMPOSITION_DATA_STATUS:
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/mesh/access.py", line 94, in __eq__
    return (self.serialize == other.serialize())
AttributeError: 'int' object has no attribute 'serialize'

2019-06-25 17:47:20,294 - INFO - tty.usbmodem0006822145041: ECDH request received
2019-06-25 17:47:20,295 - DEBUG - tty.usbmodem0006822145041: Writing: 104 bytearray(b'\x00\x16\xb7+}\x0f\xb9\x9a/\xcaK\xf6Q\xa5k\x1cCo\n\xc1\xd4\x05\xcd\x8a\x91\x04\xa3\x1fx\x8c\rk\xe1')
2019-06-25 17:47:20,295 - DEBUG - tty.usbmodem0006822145041: TX: 22680016b72b7d0fb99a2fca4bf651a56b1c436f0ac1d405cd8a9104a31f788c0d6be1
2019-06-25 17:47:20,300 - DEBUG - tty.usbmodem0006822145041: RX: 0484680000
2019-06-25 17:47:20,300 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: CmdRsp, data: {'opcode': 104, 'status': 0, 'data': bytearray(b'\x00')}}
2019-06-25 17:47:20,300 - INFO - tty.usbmodem0006822145041: EcdhSecret: {'context': 0}
2019-06-25 17:47:20,300 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.__event_handler of <__main__.Manager object at 0x103d562b0>>
2019-06-25 17:47:20,301 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 227, in __event_handler
    if event._opcode == ConfigurationClient._COMPOSITION_DATA_STATUS:
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/mesh/access.py", line 94, in __eq__
    return (self.serialize == other.serialize())
AttributeError: 'int' object has no attribute 'serialize'

2019-06-25 17:47:22,619 - DEBUG - tty.usbmodem0006822145041: RX: 2cc50000000000000022000000276fe1276661626ec4339f9527d8eef118eed9c2a56add85049ffc3c59ad0e12
2019-06-25 17:47:22,619 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: ProvComplete, data: {'context_id': 0, 'iv_index': 0, 'net_key_index': 0, 'address': 34, 'iv_update_flag': 0, 'key_refresh_flag': 0, 'device_key': bytearray(b"\'o\xe1\'fabn\xc43\x9f\x95\'\xd8\xee\xf1"), 'net_key': bytearray(b'\x18\xee\xd9\xc2\xa5j\xdd\x85\x04\x9f\xfc<Y\xad\x0e\x12')}}
2019-06-25 17:47:22,620 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.__event_handler of <__main__.Manager object at 0x103d562b0>>
2019-06-25 17:47:22,621 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 227, in __event_handler
    if event._opcode == ConfigurationClient._COMPOSITION_DATA_STATUS:
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/mesh/access.py", line 94, in __eq__
    return (self.serialize == other.serialize())
AttributeError: 'int' object has no attribute 'serialize'

2019-06-25 17:47:22,622 - INFO - tty.usbmodem0006822145041: Provisioning complete
2019-06-25 17:47:22,622 - INFO - tty.usbmodem0006822145041: 	Address(es): 0x22-0x22
2019-06-25 17:47:22,624 - INFO - tty.usbmodem0006822145041: 	Device key: 276fe1276661626ec4339f9527d8eef1
2019-06-25 17:47:22,624 - INFO - tty.usbmodem0006822145041: 	Network key: 18eed9c2a56add85049ffc3c59ad0e12
2019-06-25 17:47:22,627 - INFO - tty.usbmodem0006822145041: Adding device key to subnet 0
2019-06-25 17:47:22,629 - INFO - tty.usbmodem0006822145041: Adding publication address of root element
2019-06-25 17:47:22,629 - DEBUG - tty.usbmodem0006822145041: Writing: 156 bytearray(b'"\x00\x00\x00\'o\xe1\'fabn\xc43\x9f\x95\'\xd8\xee\xf1')
2019-06-25 17:47:22,632 - DEBUG - tty.usbmodem0006822145041: TX: 159c22000000276fe1276661626ec4339f9527d8eef1
2019-06-25 17:47:22,635 - DEBUG - tty.usbmodem0006822145041: Writing: 164 bytearray(b'"\x00')
2019-06-25 17:47:22,640 - DEBUG - tty.usbmodem0006822145041: TX: 03a42200
2019-06-25 17:47:22,640 - DEBUG - tty.usbmodem0006822145041: RX: 05849c000800
2019-06-25 17:47:22,641 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: CmdRsp, data: {'opcode': 156, 'status': 0, 'data': bytearray(b'\x08\x00')}}
2019-06-25 17:47:22,641 - INFO - tty.usbmodem0006822145041: DevkeyAdd: {'devkey_handle': 8}
2019-06-25 17:47:22,641 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.__event_handler of <__main__.Manager object at 0x103d562b0>>
2019-06-25 17:47:22,641 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 227, in __event_handler
    if event._opcode == ConfigurationClient._COMPOSITION_DATA_STATUS:
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/mesh/access.py", line 94, in __eq__
    return (self.serialize == other.serialize())
AttributeError: 'int' object has no attribute 'serialize'

2019-06-25 17:47:22,642 - DEBUG - tty.usbmodem0006822145041: RX: 0584a4000000
2019-06-25 17:47:22,642 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: CmdRsp, data: {'opcode': 164, 'status': 0, 'data': bytearray(b'\x00\x00')}}
2019-06-25 17:47:22,642 - INFO - tty.usbmodem0006822145041: AddrPublicationAdd: {'address_handle': 0}
2019-06-25 17:47:22,643 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.__event_handler of <__main__.Manager object at 0x103d562b0>>
2019-06-25 17:47:22,643 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 227, in __event_handler
    if event._opcode == ConfigurationClient._COMPOSITION_DATA_STATUS:
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/mesh/access.py", line 94, in __eq__
    return (self.serialize == other.serialize())
AttributeError: 'int' object has no attribute 'serialize'

2019-06-25 17:47:22,737 - DEBUG - tty.usbmodem0006822145041: RX: 03c20000
2019-06-25 17:47:22,738 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: ProvLinkClosed, data: {'context_id': 0, 'close_reason': 0}}
2019-06-25 17:47:22,739 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.__event_handler of <__main__.Manager object at 0x103d562b0>>
2019-06-25 17:47:22,740 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 227, in __event_handler
    if event._opcode == ConfigurationClient._COMPOSITION_DATA_STATUS:
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/mesh/access.py", line 94, in __eq__
    return (self.serialize == other.serialize())
AttributeError: 'int' object has no attribute 'serialize'

2019-06-25 17:47:22,741 - INFO - tty.usbmodem0006822145041: Provisioning link closed
2019-06-25 17:48:41,115 - DEBUG - tty.usbmodem0006822145041: RX: 04810200fe
2019-06-25 17:48:41,117 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: DeviceStarted, data: {'operating_mode': 2, 'hw_error': 0, 'data_credit_available': 254}}
2019-06-25 17:48:41,118 - INFO - tty.usbmodem0006822145041: Device rebooted.
2019-06-25 17:48:41,118 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.__event_handler of <__main__.Manager object at 0x103d562b0>>
2019-06-25 17:48:41,118 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 227, in __event_handler
    if event._opcode == ConfigurationClient._COMPOSITION_DATA_STATUS:
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/mesh/access.py", line 94, in __eq__
    return (self.serialize == other.serialize())
AttributeError: 'int' object has no attribute 'serialize'

2019-06-25 17:48:41,615 - DEBUG - tty.usbmodem0006822145041: RX: 04810200fe
2019-06-25 17:48:41,615 - DEBUG - tty.usbmodem0006822145041: parsed_packet {event: DeviceStarted, data: {'operating_mode': 2, 'hw_error': 0, 'data_credit_available': 254}}
2019-06-25 17:48:41,615 - INFO - tty.usbmodem0006822145041: Device rebooted.
2019-06-25 17:48:41,615 - ERROR - tty.usbmodem0006822145041: Exception in pkt handler <bound method Manager.__event_handler of <__main__.Manager object at 0x103d562b0>>
2019-06-25 17:48:41,615 - ERROR - tty.usbmodem0006822145041: traceback: Traceback (most recent call last):
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/aci/aci_uart.py", line 88, in process_packet
    fun(packet)
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/interactive_pyaci.py", line 227, in __event_handler
    if event._opcode == ConfigurationClient._COMPOSITION_DATA_STATUS:
  File "/Users/Tim-Mac/msc/bm-control/dev/nrf5SDKforMeshv310src/scripts/interactive_pyaci/mesh/access.py", line 94, in __eq__
    return (self.serialize == other.serialize())
AttributeError: 'int' object has no attribute 'serialize'

